version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev.api
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - db
  scraper:
    build:
      context: .
      dockerfile: Dockerfile.dev.scraper
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
    volumes:
            - ./auth-init.js:/docker-entrypoint-initdb.d/auth-init.js:ro
  frontend:
      build:
        context: .
        dockerfile: Dockerfile.dev.frontend
      volumes:
        - ./whoshittin/:/app
      ports:
        - 3000:3000
