version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev.api
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - db
  scraper:
    build:
      context: .
      dockerfile: Dockerfile.dev.scraper
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examplepassword
